services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tars_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DB_USER=postgres.pysaqdfijktldrzjlqsm
      - DB_PASS=DkoQGcMFW3dXX5QI
      - DB_NAME=postgres
      - DB_HOST=aws-1-us-east-1.pooler.supabase.com
      - DB_PORT=5432
      - GOOGLE_APPLICATION_CREDENTIALS=/app/tars.json

    volumes:
      - ./dataBase:/app/dataBase

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tars_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=sqlite3
    ports:
      - "3000:3000"
      - "222:22"
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  runner:
    image: gitea/act_runner:latest
    container_name: gitea_runner
    restart: always
    network_mode: host
    environment:
      - CONFIG_FILE=/config.yaml
      - GITEA_INSTANCE_URL=http://100.69.250.70:3000
      - GITEA_RUNNER_REGISTRATION_TOKEN=H1J60QnW4MXIjqIXESYMmLdV1Yk78MEP61Wy0edi
    volumes:
      - ./runner_data:/data
      - ./runner_data/config.yaml:/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock