services:
  db:
    image: pgvector/pgvector:pg16 # Imagen oficial con soporte para vectores
    container_name: chinese_ai_db
    restart: always
    environment:
      POSTGRES_USER: lancelot # Tu usuario habitual
      POSTGRES_PASSWORD: 9474609
      POSTGRES_DB: chinese_tutor_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistencia completa

volumes:
  postgres_data: # Definición del volumen nombrado