name: agentes_ia
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - acres==0.5.0
      - aiosqlite==0.22.1
      - annotated-doc==0.0.4
      - audioread==3.1.0
      - babel==2.18.0
      - backoff==2.2.1
      - bcrypt==5.0.0
      - beautifulsoup4==4.14.3
      - build==1.4.0
      - chromadb==1.4.0
      - ci-info==0.3.0
      - coloredlogs==15.0.1
      - colorlog==6.10.1
      - configobj==5.0.9
      - configparser==7.2.0
      - csvw==3.7.0
      - dataclasses-json==0.6.7
      - decorator==5.2.1
      - deepgram-sdk==5.3.2
      - dlinfo==2.0.0
      - durationpy==0.10
      - ebooklib==0.20
      - espeakng-loader==0.2.4
      - etelemetry==0.3.1
      - faiss-cpu==1.13.2
      - fastapi==0.128.3
      - filelock==3.20.3
      - filetype==1.2.0
      - flatbuffers==25.12.19
      - fsspec==2026.1.0
      - google-api-core==2.29.0
      - google-auth==2.47.0
      - google-cloud-texttospeech==2.34.0
      - google-genai==1.57.0
      - googleapis-common-protos==1.72.0
      - grandalf==0.8
      - groq==0.37.1
      - grpcio==1.78.0
      - grpcio-status==1.78.0
      - hf-xet==1.2.0
      - httplib2==0.31.2
      - httptools==0.7.1
      - httpx-sse==0.4.3
      - huggingface-hub==1.3.2
      - humanfriendly==10.0
      - importlib-metadata==8.7.1
      - importlib-resources==6.5.2
      - isodate==0.7.2
      - joblib==1.5.3
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - kokoro-onnx==0.3.9
      - kokoro-tts==2.3.0
      - kubernetes==34.1.0
      - langchain-classic==1.0.1
      - langchain-community==0.4.1
      - langchain-experimental==0.4.1
      - langchain-google-genai==4.2.0
      - langchain-groq==1.1.1
      - langchain-ollama==1.0.1
      - langchain-openai==1.1.7
      - langchain-tavily==0.2.16
      - langchain-text-splitters==1.1.0
      - langgraph==1.0.7
      - langgraph-checkpoint-postgres==3.0.4
      - langgraph-checkpoint-sqlite==3.0.3
      - langgraph-prebuilt==1.0.7
      - language-tags==1.2.0
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.46.0
      - looseversion==1.3.0
      - lxml==6.0.2
      - markdown-it-py==4.0.0
      - marshmallow==3.26.2
      - mdurl==0.1.2
      - mmh3==5.2.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - mypy-extensions==1.1.0
      - networkx==3.6.1
      - nibabel==5.3.3
      - nipype==1.10.0
      - numba==0.63.1
      - numpy==2.3.5
      - oauthlib==3.3.1
      - ollama==0.6.1
      - onnxruntime==1.23.2
      - opentelemetry-api==1.39.1
      - opentelemetry-exporter-otlp-proto-common==1.39.1
      - opentelemetry-exporter-otlp-proto-grpc==1.39.1
      - opentelemetry-proto==1.39.1
      - opentelemetry-sdk==1.39.1
      - opentelemetry-semantic-conventions==0.60b1
      - overrides==7.7.0
      - pandas==3.0.0
      - pathlib==1.0.1
      - pgvector==0.4.2
      - phonemizer-fork==3.3.1
      - pillow==12.1.0
      - platformdirs==4.5.1
      - pooch==1.9.0
      - posthog==5.4.0
      - proto-plus==1.27.1
      - protobuf==6.33.4
      - prov==2.1.1
      - psutil==7.2.1
      - psycopg==3.3.2
      - psycopg-binary==3.3.2
      - psycopg-pool==3.3.0
      - psycopg2-binary==2.9.11
      - puremagic==1.30
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.3
      - pydantic-settings==2.12.0
      - pydot==4.0.1
      - pygments==2.19.2
      - pymupdf==1.26.7
      - pymupdf4llm==0.2.9
      - pyparsing==3.3.1
      - pypdf==6.6.2
      - pypika==0.50.0
      - pyproject-hooks==1.2.0
      - python-dateutil==2.9.0.post0
      - python-docx==1.2.0
      - pyxnat==1.6.4
      - rdflib==7.5.0
      - referencing==0.37.0
      - requests-oauthlib==2.0.0
      - rfc3986==1.5.0
      - rich==14.2.0
      - rpds-py==0.30.0
      - rsa==4.9.1
      - scikit-learn==1.8.0
      - scipy==1.17.0
      - segments==2.3.0
      - shellingham==1.5.4
      - simplejson==3.20.2
      - six==1.17.0
      - sounddevice==0.5.5
      - soundfile==0.13.1
      - soupsieve==2.8.3
      - soxr==1.0.0
      - sqlite-vec==0.1.6
      - starlette==0.52.1
      - sympy==1.14.0
      - tabulate==0.9.0
      - termcolor==3.3.0
      - threadpoolctl==3.6.0
      - tokenizers==0.22.2
      - traits==7.1.0
      - typer==0.21.1
      - typer-slim==0.21.1
      - typing-inspect==0.9.0
      - uritemplate==4.2.0
      - urllib3==2.3.0
      - uvicorn==0.40.0
      - watchfiles==1.1.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - zipp==3.23.0