name: Deploy Tars
on:
  push:
    branches: [ "main" ] # Solo se activa cuando algo llega a main

jobs:
  deploy:
    runs-on: self-hosted # El runner vivirá en tu Xiaomi
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Docker Compose Up
        run: docker compose up -d --build
